# Default settings

device: cuda
device_options: [cuda, cpu]
pin_memory: false                 # if true: 'device' must be set to 'cpu'
num_workers: 4                    # >0: faster data loading, increased GPU usage

paths:
  log_dir: /media/Alpha/facial-reenactment/logs
  checkpoint_dir: /media/Alpha/facial-reenactment/checkpoints
  gen_dir: /media/Alpha/facial-reenactment/generated_train
  gen_test_dir: /media/Alpha/facial-reenactment/generated_test
  output_dir: ./outputs

preprocessing:
  num_frames: 8                   # number of frames +1 to extract from a video
  num_videos: 0                   # >0: number of videos to be preprocessed, =0: all videos
  overwrite: false

dataset:
  dataset_train: /home/kaan/datasets/VoxCeleb2/Preprocessed/dev/
  dataset_test: /home/kaan/datasets/VoxCeleb2/Preprocessed/test/
  csv_train: ./dataset/dataset_dev.csv
  csv_test: ./dataset/dataset_test.csv
  image_size: 128
  image_size_test: 299 
  shuffle: true                   # DataLoader: shuffle data
  augmentation:
    shuffle_frames: true          # if true: randomly select 3 frames out of 'num_frames' 
    horizontal_flip: true         # if true: randomly flip data
    rotation_angle: 15            # >0: randomly rotate data

train:
  test: true                      # test model after each epoch
  continue_id: null               # continue training from checkpoint
  epochs: 30
  batch_size: 8
  lr_g: 0.0001
  lr_d: 0.0001
  checkpoint_freq: 5000           # frequency [iterations] to save checkpoints
  log_freq: 1000                  # frequency [iterations] to log generated images
  gan_type: wgan-gp
  grad_clip: 1                    # use gradient clipping
  loss_weights:
    l_adv: 0.01
    l_rec: 1
    l_self: 1
    l_triple: 1
    l_percep: 0.1
    l_tv: 1.0e-4
  optimizer:
    beta1: 0.5
    beta2: 0.9
    weight_decay: 5.0e-4
    scheduler_step_size: 1
    scheduler_gamma: 0.1
